apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker:
      dockerfile: Dockerfile
    image: gcr.io/tfx-pipeline-272806/tfx-pipeline
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
kind: Config
